import Head from "next/head";
import Link from "next/link";
import { Button, Card } from "react-bootstrap";
import styles from "../styles/Home.module.css";

export default function Home({ data }) {
  let products = data?.products?.map((product) => {
    return (
      <Card style={{ width: "18rem", margin: "8px" }} key={product.id}>
        <Card.Img variant="top" src={product.thumbnail} />
        <Card.Body>
          <Card.Title>{product.title}</Card.Title>
          <Card.Title>₹ {product.price}</Card.Title>
          <Card.Text>{product.description}</Card.Text>
          <Button variant="primary">add</Button>
          <div className="card-action">
             <Link href={'/product/[id]'} as={`/product/${product.id}`}>
              <a>View Product</a>
              </Link>
          </div>
        </Card.Body>
      </Card>
    );
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Zero-price</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className="mt-3"
        style={{
          display: "flex",
          flexWrap: "wrap",
          justifyContent: "flex-end",
        }}
      >
        {products}
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://dummyjson.com/products`);
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
}
