import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { Button, Card } from "react-bootstrap";
import styles from "../styles/Home.module.css";

export default function Home({ data }) {

  const [visible, setVisible] = useState(4)

const showMoreProduct = () => { 
   setVisible((preValue) => preValue + 4);

 }


  let products = data?.products?.slice(0, visible).map((product) => {
    return (
      <Card style={{ width: "18rem", margin: "8px" }} key={product.id}>
        <Link href={'/product/[id]'} as={`/product/${product.id}`}>
        <Card.Img variant="top" src={product.thumbnail} />
        </Link>
        <Card.Body>
          <Card.Title>{product.title}</Card.Title>
          <Card.Title>₹ {product.price}</Card.Title>
          <Card.Text>{product.description}</Card.Text>
          <Button variant="primary"  onClick={()=>AddToCart()}>add</Button>
        </Card.Body>
      </Card>
    );
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Zero-price</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className="mt-3"
        style={{
          display: "flex",
          flexWrap: "wrap",
          justifyContent: "flex-end",
        }}
      >
        {products}
      </div>
      <button onClick={showMoreProduct}>Load More</button>
    </div>
  );
}

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://dummyjson.com/products`);
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
}

const AddToCart = async ()=>{
  const res =  await fetch(`${baseUrl}/api/cart`,{
    method:"PUT",
    headers:{
      "Content-Type":"application/json",
      "Authorization":cookie.token
    },
    body:JSON.stringify({
     quantity,
     productId:product._id
    })
  })
const res2 = await res.json()
if(res2.error){
  console.log("error")
}
console.log("added")
}
